# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.IntegerField()),
                ('crawls_per_month', models.IntegerField()),
                ('connected_accounts', models.IntegerField()),
            ],
        ),
    ]
