# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_accounts', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='connected_accounts',
        ),
    ]
