# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171030_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconnector',
            name='final_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='final_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
